import {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} from '@google/generative-ai';
import { saveCaseAdvisorEntry } from '@/lib/localDb';

const MODEL_NAME = 'gemini-2.5-flash';

export async function POST(req) {
  const formData = await req.json();

  const locale = formData.locale || 'en';
  const languageMap = {
    en: "English",
    hi: "Hindi",
    mr: "Marathi",
    te: "Telugu"
  };
  const targetLanguage = languageMap[locale] || "English";

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  const model = genAI.getGenerativeModel({ model: MODEL_NAME });

  // --- FINAL SYSTEM INSTRUCTION ---
  const systemInstruction = `You are "Advocat-Analysis Engine," a Senior Indian Civil Lawyer acting as a strategic case strategist.

**YOUR MISSION:**
Do not just recite the law. Analyze the *winnability* of this case. Your job is to find the "Golden Thread" that wins the case or the "Fatal Flaw" that loses it.

**TONE:** Professional, strategic, and brutally honest about risks. Explain legal terms simply (e.g., "Locus Standi" -> "Right to sue").

**CRITICAL RULES:**
1. **Civil Only:** Reject criminal matters immediately.
2. **Specific Citations:** Use "Section X of Act Y."
3. **State Specifics:** Apply state-specific amendments/rules if location is provided.

**MANDATORY RESPONSE STRUCTURE (Markdown):**

### 1. Case Strength Assessment (The Verdict)
* **Prima Facie Strength:** [Rate: Strong / Moderate / Weak]. Explain *why* in one sentence.
* **Jurisdiction Check:** Confirm if the chosen court is correct (Sec 20 CPC).

### 2. Legal Framework (The Foundation)
* **Primary Acts:** List key Acts (e.g., "Specific Relief Act, 1963").
* **Key Sections:** Cite specific sections and *apply them to the facts*.

### 3. Evidence Audit & The "Golden Thread"
* **Current Strength:** Analyze provided evidence. Distinguish between *Primary Evidence* (Original docs) and *Secondary Evidence* (Copies/Chats).
* **The "Missing Link":** What ONE piece of evidence is missing? (e.g., "You need a Bank Certificate under Sec 65B").
* **65B Warning:** If electronic evidence (chats/emails) is key, warn about the mandatory Section 65B Affidavit.

### 4. The "Devil's Advocate" (Risks)
* **Opponent's Best Move:** What is the strongest argument the other side will use?
* **Your Counter-Move:** How to prepare for that attack *today*.

### 5. The Settlement Angle (Strategic Exit)
* **ADR Potential:** Is this case suitable for Mediation or Lok Adalat?
* **Leverage:** What fact gives the user leverage to settle out of court?

### 6. Strategic Action Plan
* **Immediate:** (What to do in next 24 hours)
* **Short Term:** (Drafting/Notices)
* **Long Term:** (Filing suit)

### 7. Where to File (Jurisdiction Search)
* **The Correct Court:** State the exact type of court or tribunal that has jurisdiction over this specific matter.
* **Smart Search:** Provide a Google Maps search link exactly in this markdown format:
[📍 Find this court on Google Maps](https://www.google.com/maps/search/?api=1&query=Exact+Court+Name+In+City)
(Replace "Exact+Court+Name+In+City" with the specific court name and user's city, using '+' for spaces).

**DISCLAIMER:** *"This analysis is educational strategy generated by AI. It is not a substitute for professional legal counsel."*`;

  const generationConfig = {
    temperature: 0.2, 
    topK: 1,
    topP: 1,
    maxOutputTokens: 8192, // Increased to prevent mid-sentence cutoffs
  };
  
  const safetySettings = [
    { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
  ];

  const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

  async function generateWithRetry(requestPayload, maxRetries = 4) {
    for (let attempt = 0; attempt <= maxRetries; attempt++) {
      try {
        return await model.generateContent(requestPayload);
      } catch (err) {
        const is503 = err.status === 503 || err.message?.includes('503');
        const is429 = err.status === 429 || err.message?.includes('429');
        const retryable = is503 || is429;
        if (!retryable || attempt === maxRetries) throw err;
        // Parse retry delay from error message if available, else exponential backoff
        const match = err.message?.match(/Please retry in ([\d.]+)s/);
        const delay = match ? parseFloat(match[1]) * 1000 : Math.min(2000 * 2 ** attempt, 30000);
        console.log(`Attempt ${attempt + 1} failed (${err.status}). Retrying in ${Math.round(delay / 1000)}s...`);
        await sleep(delay);
      }
    }
  }

  try {
    // --- PRE-VALIDATION: Check for gibberish input ---
    // --- LAYER 1: Fast JS heuristic check ---
    const gibberishPatterns = [
      /\b(asdf|qwerty|zxcvb|hjkl|uiop|bnm|qaz|wsx|edc|rfv|tgb|yhn|ujm|ijk)\b/i,
      /\b(lorem|ipsum|dolor|sit amet)\b/i,
      /\b(hello world|foo bar|test test|blah blah|abc xyz|xyz abc)\b/i,
    ];
    const descWords = (formData.description || '').trim().split(/\s+/);
    const titleWords = (formData.caseTitle || '').trim().split(/\s+/);
    const allText = `${formData.caseTitle} ${formData.description} ${formData.reliefSought}`;
    const digitRatio = (allText.replace(/[^0-9]/g, '').length) / Math.max(allText.replace(/\s/g, '').length, 1);
    const avgWordLen = allText.replace(/[^a-zA-Z ]/g, '').split(/\s+/).reduce((s, w) => s + w.length, 0) / Math.max(descWords.length, 1);

    const isHeuristicGibberish =
      gibberishPatterns.some(p => p.test(allText)) ||
      digitRatio > 0.45 ||
      descWords.length < 8 ||
      avgWordLen < 2.5;

    if (isHeuristicGibberish) {
      return new Response(
        JSON.stringify({ message: 'Invalid input: Please provide a real legal case description. Random text, numbers, or gibberish cannot be analyzed.' }),
        { status: 400 }
      );
    }

    // --- LAYER 2: Gemini semantic check ---
    const validationPrompt = `You are a strict input validator for a legal case analysis tool.

INPUTS:
Title: "${formData.caseTitle}"
Description: "${formData.description}"
Relief Sought: "${formData.reliefSought}"

Does this describe a real or plausible legal dispute between two parties, in any language (English, Hindi, Marathi, Telugu, etc.)?

Examples of INVALID inputs:
- "1234 abc xyz 9999" / "asdfgh blah blah 777" / "qwerty 000"
- Random trivia facts or numbers with no dispute
- Placeholder text

Examples of VALID inputs:
- "My landlord refused to return security deposit after I vacated the flat"
- "Contractor took advance payment but did not complete construction work"
- "मेरे पड़ोसी ने मेरी जमीन पर कब्जा कर लिया"

Reply with one word only — VALID or INVALID.`;

    const validationResult = await generateWithRetry({
      contents: [{ role: 'user', parts: [{ text: validationPrompt }] }],
      generationConfig: { temperature: 0, maxOutputTokens: 5 },
      safetySettings,
    });

    const validationText = validationResult.response.text().trim().toUpperCase();
    if (validationText.startsWith('INVALID')) {
      return new Response(
        JSON.stringify({ message: 'Invalid input: Please provide a real legal case description. Random text, numbers, or gibberish cannot be analyzed.' }),
        { status: 400 }
      );
    }
    // --- END PRE-VALIDATION ---

    const prompt = `ACT AS A SENIOR INDIAN BASED LAWYER. Analyze this civil case:
    
    **CLIENT DETAILS:**
    - **Title:** ${formData.caseTitle}
    - **Type:** ${formData.caseType}
    - **Location:** ${formData.city}, ${formData.state}
    
    **FACTS:**
    "${formData.description}"
    
    **GOAL (Relief Sought):**
    "${formData.reliefSought}" (Value: ${formData.suitValue})
    
    **HISTORY:**
    - Cause Date: ${formData.causeDate}
    - Prior Actions: ${formData.priorActions}
    
    **EVIDENCE FILE:**
    - Witnesses: ${JSON.stringify(formData.witnesses)}
    - Physical/Docs: ${JSON.stringify(formData.evidence)}
    - 65B Status: ${formData.certificateStatus}
    
    Provide the detailed strategic breakdown as per system instructions. Be extremely specific about RISKS and COUNTER-MOVES.
    
    **CRITICAL INSTRUCTION:** You MUST generate your ENTIRE response (including headings) in ${targetLanguage}.`;

    const result = await generateWithRetry({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig,
      safetySettings,
      systemInstruction,
    });

    const response = result.response;
    const text = response.text();

    // Save to case advisor history if user email is present
    if (formData.email) {
      try {
        saveCaseAdvisorEntry({
          id: `ca-${Date.now()}`,
          email: formData.email,
          caseTitle: formData.caseTitle || 'Untitled Case',
          caseType: formData.caseType || '',
          city: formData.city || '',
          state: formData.state || '',
          reliefSought: formData.reliefSought || '',
          result: text,
          createdAt: new Date().toISOString(),
        });
      } catch (err) {
        console.error('Failed to save case advisor history:', err);
      }
    }

    return new Response(JSON.stringify({ text }), { status: 200 });
  } catch (error) {
    console.error('Gemini API error:', error);
    const is503 = error.status === 503 || error.message?.includes('503');
    const is429 = error.status === 429 || error.message?.includes('429');
    const status = is503 ? 503 : is429 ? 429 : 500;
    const msg = is503
      ? 'AI servers are overloaded. Please try again in a moment.'
      : is429
      ? 'API quota exceeded. Please try again later.'
      : 'AI Processing Error';
    return new Response(JSON.stringify({ message: msg }), { status });
  }
}