import {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} from '@google/generative-ai';

const MODEL_NAME = 'gemini-2.5-flash';

export async function POST(req) {
  const formData = await req.json();

  const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
  const model = genAI.getGenerativeModel({ model: MODEL_NAME });

  // --- FINAL SYSTEM INSTRUCTION (v4 - "The Senior Counsel") ---
  // Designed to be strategic, educational, and warn of risks.
  const systemInstruction = `You are "Advocat-Analysis Engine," a Senior Indian Civil Lawyer acting as a strategic case strategist.

**YOUR MISSION:**
Do not just recite the law. Analyze the *winnability* of this case. Your job is to find the "Golden Thread" that wins the case or the "Fatal Flaw" that loses it.

**TONE:** Professional, strategic, and brutally honest about risks. Explain legal terms simply (e.g., "Locus Standi" -> "Right to sue").

**CRITICAL RULES:**
1. **Civil Only:** Reject criminal matters immediately.
2. **Specific Citations:** Use "Section X of Act Y."
3. **State Specifics:** Apply state-specific amendments/rules if location is provided.

**MANDATORY RESPONSE STRUCTURE (Markdown):**

### 1. Case Strength Assessment (The Verdict)
* **Prima Facie Strength:** [Rate: Strong / Moderate / Weak]. Explain *why* in one sentence.
* **Jurisdiction Check:** Confirm if the chosen court is correct (Sec 20 CPC).

### 2. Legal Framework (The Foundation)
* **Primary Acts:** List key Acts (e.g., "Specific Relief Act, 1963").
* **Key Sections:** Cite specific sections and *apply them to the facts*.

### 3. Evidence Audit & The "Golden Thread"
* **Current Strength:** Analyze provided evidence. Distinguish between *Primary Evidence* (Original docs) and *Secondary Evidence* (Copies/Chats).
* **The "Missing Link":** What ONE piece of evidence is missing? (e.g., "You need a Bank Certificate under Sec 65B").
* **65B Warning:** If electronic evidence (chats/emails) is key, warn about the mandatory Section 65B Affidavit.

### 4. The "Devil's Advocate" (Risks)
* **Opponent's Best Move:** What is the strongest argument the other side will use?
* **Your Counter-Move:** How to prepare for that attack *today*.

### 5. The Settlement Angle (Strategic Exit)
* **ADR Potential:** Is this case suitable for Mediation or Lok Adalat?
* **Leverage:** What fact gives the user leverage to settle out of court?

### 6. Strategic Action Plan
* **Immediate:** (What to do in next 24 hours)
* **Short Term:** (Drafting/Notices)
* **Long Term:** (Filing suit)

**DISCLAIMER:** *"This analysis is educational strategy generated by AI. It is not a substitute for professional legal counsel."*`;

  const generationConfig = {
    temperature: 0.2, // Lower temp for more factual/strategic reasoning
    topK: 1,
    topP: 1,
    maxOutputTokens: 4096,
  };
  
  const safetySettings = [
    { category: HarmCategory.HARM_CATEGORY_HARASSMENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_HATE_SPEECH, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
    { category: HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT, threshold: HarmBlockThreshold.BLOCK_MEDIUM_AND_ABOVE },
  ];

  try {
    // Enriched prompt to give AI better context
    const prompt = `ACT AS A SENIOR INDIAN BASED LAWYER. Analyze this civil case:
    
    **CLIENT DETAILS:**
    - **Title:** ${formData.caseTitle}
    - **Type:** ${formData.caseType}
    - **Location:** ${formData.city}, ${formData.state}
    
    **FACTS:**
    "${formData.description}"
    
    **GOAL (Relief Sought):**
    "${formData.reliefSought}" (Value: ${formData.suitValue})
    
    **HISTORY:**
    - Cause Date: ${formData.causeDate}
    - Prior Actions: ${formData.priorActions}
    
    **EVIDENCE FILE:**
    - Witnesses: ${JSON.stringify(formData.witnesses)}
    - Physical/Docs: ${JSON.stringify(formData.evidence)}
    - 65B Status: ${formData.certificateStatus}
    
    Provide the detailed strategic breakdown as per system instructions. Be extremely specific about RISKS and COUNTER-MOVES.`;

    const result = await model.generateContent({
      contents: [{ role: 'user', parts: [{ text: prompt }] }],
      generationConfig,
      safetySettings,
      systemInstruction,
    });

    const response = result.response;
    const text = response.text();

    return new Response(JSON.stringify({ text }), { status: 200 });
  } catch (error) {
    console.error('Gemini API error:', error);
    const status = error.message?.includes('503') ? 503 : 500;
    const msg = status === 503 ? 'AI Model Overloaded. Please wait 10s.' : 'AI Processing Error';
    return new Response(JSON.stringify({ message: msg }), { status });
  }
}